server:
  port: 8081
spring:
  application:
    name: dubboProvider
dubbo:
  registry:
    address: zookeeper://114.132.198.119:2181
    simplified: true
  metadata-report:
    address: zookeeper://114.132.198.119:2181
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: cn.caber.provider.dubbo

